schema_version = "1.0.0"

id = "apply_modifiers_with_shape_keys"
version = "1.1.0"
name = "Apply modifier with shape keys"
tagline = "Applies modifiers on objects even if they have shape keys"
maintainer = "Wayne Dixon <wayne@cgcookie.com>"

type = "add-on"

website = "https://github.com/CGCookie/apply_modifiers_with_shape_keys"

tags = ["Animation", "Modeling", "Rigging"]

blender_version_min = "4.3.2"

license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  "images/",
  ".*",
  "*.blend",
  "*.blend[0123456789]",
  "*.md",
  "*.zip",
]
